# Generated by Django 5.0.4 on 2024-09-22 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0006_complaint_resolution_delete_prediction'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='resolution_status',
            field=models.CharField(blank=True, choices=[('Satisfactory', 'Satisfactory'), ('Unsatisfactory', 'Unsatisfactory')], max_length=15, null=True),
        ),
    ]
