# Generated by Django 5.0.4 on 2024-09-22 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0007_complaint_resolution_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Resolved', 'Resolved'), ('Rejected', 'Rejected')], default='Pending', max_length=10),
        ),
    ]
