# Generated by Django 5.0.4 on 2024-09-22 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0008_alter_complaint_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='resolution_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
