# Generated by Django 5.0.4 on 2024-09-22 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0009_complaint_resolution_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='resolution_status',
            field=models.CharField(blank=True, choices=[('Satisfactory', 'Satisfactory'), ('Unsatisfactory', 'Unsatisfactory'), ('Pending', 'Pending')], default='Pending', max_length=15, null=True),
        ),
    ]
