# Generated by Django 5.0.4 on 2024-10-20 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0010_alter_complaint_resolution_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientprofile',
            name='status',
        ),
    ]
