# Generated by Django 5.0.4 on 2025-01-24 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0011_remove_clientprofile_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='team_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
