# Generated by Django 5.0.4 on 2025-01-24 12:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0012_project_team_id'),
        ('freelancer', '0009_alter_teammember_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='team_id',
        ),
        migrations.AddField(
            model_name='project',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='freelancer.team'),
        ),
    ]
