# Generated by Django 5.0.4 on 2025-02-03 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0016_jobinvitation'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobinvitation',
            name='meeting_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobinvitation',
            name='meeting_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
