# Generated by Django 5.0.4 on 2025-02-05 07:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0021_jobinvitation_benefits_jobinvitation_bond_period_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventAndQuiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('date', models.DateTimeField()),
                ('type', models.CharField(choices=[('event', 'Event'), ('quiz', 'Quiz')], max_length=10)),
                ('type_of_event', models.CharField(blank=True, choices=[('webinar', 'Webinar'), ('workshop', 'Workshop'), ('conference', 'Conference')], max_length=20, null=True)),
                ('poster', models.FileField(blank=True, null=True, upload_to='event_posters/')),
                ('max_participants', models.PositiveIntegerField(blank=True, null=True)),
                ('online_link', models.URLField(blank=True, null=True)),
                ('certificate_provided', models.BooleanField(default=False)),
                ('prize_enabled', models.BooleanField(default=False)),
                ('prize_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
