# Generated by Django 5.0.4 on 2025-02-06 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0024_eventandquiz_quiz_file_quizquestion'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventandquiz',
            name='event_status',
            field=models.CharField(choices=[('upcoming', 'Upcoming'), ('done', 'Done')], default='upcoming', max_length=20),
        ),
        migrations.AddField(
            model_name='eventandquiz',
            name='number_of_registrations',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='eventandquiz',
            name='registration_end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='eventandquiz',
            name='registration_status',
            field=models.CharField(choices=[('open', 'Open'), ('closed', 'Closed')], default='open', max_length=10),
        ),
    ]
