# Generated by Django 5.0.4 on 2025-02-06 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0025_eventandquiz_event_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventandquiz',
            name='duration',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
