# Generated by Django 5.0.4 on 2025-03-02 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0030_eventandquiz_certificate_template'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventandquiz',
            name='approval_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', help_text='Approval status of the event/quiz', max_length=20),
        ),
        migrations.AddField(
            model_name='eventandquiz',
            name='rejection_reason',
            field=models.TextField(blank=True, help_text='Reason for rejection if the event/quiz is rejected', null=True),
        ),
    ]
