# Generated by Django 5.0.4 on 2024-10-03 00:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_cancellationrequest_reason'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='refundpayment',
            name='contract',
        ),
    ]
