# Generated by Django 5.0.4 on 2024-10-03 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_refundpayment_contract'),
    ]

    operations = [
        migrations.AddField(
            model_name='refundpayment',
            name='compensation_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='refundpayment',
            name='total_paid',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
