# Generated by Django 5.0.4 on 2024-10-20 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_refundpayment_compensation_amount_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='register',
            name='status',
        ),
        migrations.AddField(
            model_name='emailverification',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='passwordreset',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
