# Generated by Django 5.0.4 on 2024-10-26 06:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0011_remove_clientprofile_status'),
        ('core', '0007_remove_register_status_emailverification_expires_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='refundpayment',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='client.project'),
        ),
    ]
