# Generated by Django 5.0.4 on 2025-03-03 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_refundpayment_project'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('basic', 'Basic Plan'), ('standard', 'Standard Plan'), ('pro', 'Pro Plan'), ('ultimate', 'Ultimate Plan')], max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('duration', models.CharField(max_length=20)),
                ('features', models.TextField()),
            ],
        ),
    ]
