# Generated by Django 5.0.4 on 2024-09-19 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freelancer', '0002_document'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='resume_file',
            field=models.FileField(blank=True, null=True, upload_to='resume/'),
        ),
    ]
