# Generated by Django 5.0.4 on 2024-09-20 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freelancer', '0003_alter_document_resume_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='cover_images/'),
        ),
    ]
