# Generated by Django 5.0.4 on 2025-01-22 23:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freelancer', '0006_team_teaminvitation_teammember'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposal',
            name='team_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='freelancer.team'),
        ),
    ]
