# Generated by Django 5.0.4 on 2025-01-24 06:25

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freelancer', '0007_proposal_team_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teaminvitation',
            name='is_accepted',
        ),
        migrations.AddField(
            model_name='teaminvitation',
            name='expires_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='teaminvitation',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='teammember',
            name='salary_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=5, null=True),
        ),
    ]
