# Generated by Django 5.0.4 on 2025-01-29 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freelancer', '0010_salarypayment'),
    ]

    operations = [
        migrations.AddField(
            model_name='salarypayment',
            name='status',
            field=models.CharField(default='pending', max_length=20),
        ),
    ]
