# Generated by Django 5.0.4 on 2025-02-03 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freelancer', '0011_salarypayment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='freelancerprofile',
            name='hiring_status',
            field=models.CharField(choices=[('NOT_HIRED', 'Not Hired'), ('HIRED', 'Hired')], default='NOT_HIRED', max_length=20),
        ),
        migrations.AddField(
            model_name='freelancerprofile',
            name='is_open_to_work',
            field=models.BooleanField(default=False),
        ),
    ]
